In [ ]:
import numpy as np 
import requests
from bs4 import BeautifulSoup
import time
import pandas as pd
import time
import warnings 
warnings.filterwarnings('ignore')

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
ko150 = pd.read_csv('/content/drive/MyDrive/AntHouse/0.Data/enterprise/kospi200_50/new/kospi_150.csv')
ko150.drop(columns='ticker', inplace=True)
ko150

In [ ]:
def naming_all(df,n): #n은 시작할 번호 0~시작
    cnt=0
    num= df.shape[0]
    print("0은 네이밍 시작, 1은 네이밍 종료, 2는 pass 입니다.")
    print('회사당 2개의 네이밍을 진행해주세요.')
    for i in range(n,df.shape[0]):
        print(df.iloc[i,0],'의 네이밍 여부를 선택해주세요.')
        yn = input('숫자 : ')
        
        if yn == '2':  # 다음기업 이동
            continue
        elif yn=='1': # 네이밍 종료
            break
        elif yn=='0': # 네이밍 하기 
            for _ in range(2):
                name = input()
                if name=='.': # 해당 턴 종료
                    break
                else:
                    ls=list(ko150.iloc[i][1:])
                    name = name+f'({df.iloc[i,0]})'
                    ls.insert(0,name)
                    # print(cnt)
                    df.loc[cnt+num] = ls #맨 끝에 누적으로 추가
                    # print(cnt+num)
                    cnt += 1
    return df

In [ ]:
naming_all(ko150,0)

0은 네이밍 시작, 1은 네이밍 종료, 2는 pass 입니다.
회사당 2개의 네이밍을 진행해주세요.
일진머티리얼즈 의 네이밍 여부를 선택해주세요.
숫자 : 0
일진머티리얼
일진 머티리얼
GS리테일 의 네이밍 여부를 선택해주세요.
숫자 : 0
gs리테일
지에스리테일
한진칼 의 네이밍 여부를 선택해주세요.
숫자 : 0
한진kal
한진 칼
롯데쇼핑 의 네이밍 여부를 선택해주세요.
숫자 : 0
lotte쇼핑
롯데 쇼핑
제일기획 의 네이밍 여부를 선택해주세요.
숫자 : 0
제일 기획
cheil기획
한화생명 의 네이밍 여부를 선택해주세요.
숫자 : 0
한화 생명
hanwhalife
키움증권 의 네이밍 여부를 선택해주세요.
숫자 : 0
키움 증권
kiwoom증권
CJ 의 네이밍 여부를 선택해주세요.
숫자 : 0
cj
씨제이
한솔케미칼 의 네이밍 여부를 선택해주세요.
숫자 : 0
한솔 케미칼
hansol케미칼
한화시스템 의 네이밍 여부를 선택해주세요.
숫자 : 0
한화 시스템
hanwha시스템
BNK금융지주 의 네이밍 여부를 선택해주세요.
숫자 : 0
bnk금융지주
bnk금융
한전기술 의 네이밍 여부를 선택해주세요.
숫자 : 0
한전 기술
kepco
신세계 의 네이밍 여부를 선택해주세요.
숫자 : 0
ssg
SSG
동원산업 의 네이밍 여부를 선택해주세요.
숫자 : 0
동원 산업
dwml
LS 의 네이밍 여부를 선택해주세요.
숫자 : 0
ls
엘에쓰
두산퓨얼셀 의 네이밍 여부를 선택해주세요.
숫자 : 0
두산 퓨얼셀
doosan퓨얼셀
에스원 의 네이밍 여부를 선택해주세요.
숫자 : 0
s1
S1
대우조선해양 의 네이밍 여부를 선택해주세요.
숫자 : 0
대우 조선해양
대우조선 해양
휠라홀딩스 의 네이밍 여부를 선택해주세요.
숫자 : 0
휠라홀딩
휠라 홀딩스
OCI 의 네이밍 여부를 선택해주세요.
숫자 : 0
oci
오씨아이
CJ대한통운 의 네이밍 여부를 선택해주세요.
숫자 : 0
cj대한통운
CJ 대한통운
한화 의 네이밍 여부를 선택해주세요.
숫자 : 0
hanwha
HANWHA
DB하이텍 의 네이밍 여부를 선택해주세요.
숫자 : 0
db하이텍
디비하이텍
대한전선 의 네이밍 여부를 선택해주세요.
숫자 : 0
대한 전선
taihan
HL만도 의 네이밍 여부를 선택해주세요.
숫자 : 0
hl만도
에이치엘만도
농심 의 네이밍 여부를 선택해주세요.
숫자 : 0
ns
NS
GS건설 의 네이밍 여부를 선택해주세요.
숫자 : 0
gs건설
지에스건설
한미사이언스 의 네이밍 여부를 선택해주세요.
숫자 : 0
한미 사이언스
hanmi사이언스
동서 의 네이밍 여부를 선택해주세요.
숫자 : 0
dongsuh
DONGSUH
KCC 의 네이밍 여부를 선택해주세요.
숫자 : 0
kcc
케이씨씨
하이트진로 의 네이밍 여부를 선택해주세요.
숫자 : 0
hitejinro
HITEJINRO
영원무역 의 네이밍 여부를 선택해주세요.
숫자 : 0
영원 무역
youngone
대우건설 의 네이밍 여부를 선택해주세요.
숫자 : 0
대우 건설
daewoo건설
오뚜기 의 네이밍 여부를 선택해주세요.
숫자 : 0
ottogi
OTTOGI
대웅제약 의 네이밍 여부를 선택해주세요.
숫자 : 0
대웅 제약
daewoong
효성첨단소재 의 네이밍 여부를 선택해주세요.
숫자 : 0
효성첨단 소재
효성 첨단소재
효성티앤씨 의 네이밍 여부를 선택해주세요.
숫자 : 0
효성tnc
효성TNC
LIG넥스원 의 네이밍 여부를 선택해주세요.
숫자 : 0
lig넥스원
엘아이지넥스원
두산 의 네이밍 여부를 선택해주세요.
숫자 : 0
doosan
DOOSAN
롯데정밀화학 의 네이밍 여부를 선택해주세요.
숫자 : 0
롯데 정밀화학
lotte정밀화학
효성 의 네이밍 여부를 선택해주세요.
숫자 : 0
hyosung
HYOSUNG
롯데칠성 의 네이밍 여부를 선택해주세요.
숫자 : 0
롯데 칠성
lotte칠성
녹십자 의 네이밍 여부를 선택해주세요.
숫자 : 0
gccorp
GCCORP
DL이앤씨 의 네이밍 여부를 선택해주세요.
숫자 : 0
dl이앤씨
디엘이앤씨
현대위아 의 네이밍 여부를 선택해주세요.
숫자 : 0
현대 위아
hyundai위아
현대두산인프라코어 의 네이밍 여부를 선택해주세요.
숫자 : 0
현대두산 인프라코어
현대 두산인프라코어
한전KPS 의 네이밍 여부를 선택해주세요.
숫자 : 0
한전kps
한전 KPS
현대백화점 의 네이밍 여부를 선택해주세요.
숫자 : 0
현백
현대 백화점
SK케미칼 의 네이밍 여부를 선택해주세요.
숫자 : 0
sk케미칼
에스케이케미칼
LS ELECTRIC 의 네이밍 여부를 선택해주세요.
숫자 : 0
ls electic
LSELECTRIC

,name,매출액(억원),영업이익(억원),당기순이익(억원),영업이익률(%),순이익률(%),ROE(지배주주%),부채비율(%),당좌비율(%),유보율(%),EPS(원),PER(배),BPS(원),PBR(배),주당배당금(원),시가배당률(%),배당성향(%)
0,일진머티리얼즈,7943,984,711,12.39,8.95,6.11,29.96(21),299.36(21),"4,137.52(21)",1486,43.46,27199,2.38,300,0.22(21),22.04(21)
1,GS리테일,111676,2175,1017,1.95,0.91,2.66,114.21(21),39.34(21),"3,875.77(21)",1033,27.4,39697,0.71,995,3.95(21),15.04(21)
2,한진칼,2020,160,8470,7.92,419.31,42.98,105.83(21),24.64(21),505.18(21),12943,3.21,36567,1.14,-,-,-
3,롯데쇼핑,155690,4660,759,2.99,0.49,0.4,183.35(21),51.72(21),"8,887.52(21)",1412,66.63,351481,0.27,2846,3.21(21),-27.08(21)
4,제일기획,41804,3229,2242,7.72,5.36,19.03,125.51(21),161.92(21),"6,385.50(21)",1932,11.44,12034,1.84,1117,4.33(21),60.59(21)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,현대 백화점(현대백화점),48202,3594,2738,7.46,5.68,4.84,71.64(21),46.35(21),"3,829.64(21)",9327,6.87,210443,0.3,1180,1.46(21),12.69(21)
146,sk케미칼(SK케미칼),"20,896(21)","5,552(21)","2,687(21)",26.57(21),12.86(21),11.19(21),54.11(21),58.95(21),"1,999.64(21)","8,521(21)",17.49(21),"105,002(21)",1.42(21),"3,000(21)",2.01(21),34.95(21)
147,에스케이케미칼(SK케미칼),"20,896(21)","5,552(21)","2,687(21)",26.57(21),12.86(21),11.19(21),54.11(21),58.95(21),"1,999.64(21)","8,521(21)",17.49(21),"105,002(21)",1.42(21),"3,000(21)",2.01(21),34.95(21)
148,ls electic(LS ELECTRIC),32565,2171,1205,6.67,3.7,7.83,89.81(21),162.06(21),901.85(21),3986,13.17,53520,0.98,1196,1.79(21),34.61(21)
149,LSELECTRIC(LS ELECTRIC),32565,2171,1205,6.67,3.7,7.83,89.81(21),162.06(21),901.85(21),3986,13.17,53520,0.98,1196,1.79(21),34.61(21)

In [ ]:
ko150.to_csv('kospi150_rename1.csv', index=False)
ko150

,name,매출액(억원),영업이익(억원),당기순이익(억원),영업이익률(%),순이익률(%),ROE(%),부채비율(%),당좌비율(%),유보율(%),EPS(원),PER(배),BPS(원),PBR(배),주당배당금(원),시가배당률(%),배당성향(%)
0,일진머티리얼즈,7943,984,711,12.39,8.95,6.11,29.96(21),299.36(21),"4,137.52(21)",1486,43.46,27199,2.38,300,0.22(21),22.04(21)
1,GS리테일,111676,2175,1017,1.95,0.91,2.66,114.21(21),39.34(21),"3,875.77(21)",1033,27.4,39697,0.71,995,3.95(21),15.04(21)
2,한진칼,2020,160,8470,7.92,419.31,42.98,105.83(21),24.64(21),505.18(21),12943,3.21,36567,1.14,-,-,-
3,롯데쇼핑,155690,4660,759,2.99,0.49,0.4,183.35(21),51.72(21),"8,887.52(21)",1412,66.63,351481,0.27,2846,3.21(21),-27.08(21)
4,제일기획,41804,3229,2242,7.72,5.36,19.03,125.51(21),161.92(21),"6,385.50(21)",1932,11.44,12034,1.84,1117,4.33(21),60.59(21)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,현대 백화점(현대백화점),48202,3594,2738,7.46,5.68,4.84,71.64(21),46.35(21),"3,829.64(21)",9327,6.87,210443,0.3,1180,1.46(21),12.69(21)
146,sk케미칼(SK케미칼),"20,896(21)","5,552(21)","2,687(21)",26.57(21),12.86(21),11.19(21),54.11(21),58.95(21),"1,999.64(21)","8,521(21)",17.49(21),"105,002(21)",1.42(21),"3,000(21)",2.01(21),34.95(21)
147,에스케이케미칼(SK케미칼),"20,896(21)","5,552(21)","2,687(21)",26.57(21),12.86(21),11.19(21),54.11(21),58.95(21),"1,999.64(21)","8,521(21)",17.49(21),"105,002(21)",1.42(21),"3,000(21)",2.01(21),34.95(21)
148,ls electic(LS ELECTRIC),32565,2171,1205,6.67,3.7,7.83,89.81(21),162.06(21),901.85(21),3986,13.17,53520,0.98,1196,1.79(21),34.61(21)
149,LSELECTRIC(LS ELECTRIC),32565,2171,1205,6.67,3.7,7.83,89.81(21),162.06(21),901.85(21),3986,13.17,53520,0.98,1196,1.79(21),34.61(21)